[shell]
program = "wsl"
args = ["/bin/bash", "-c", "tmux", "new-session", "-A", "-s", "amg"]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

